# Generated by Django 4.2.7 on 2026-01-15 15:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao_code', models.CharField(max_length=4, unique=True)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('has_lounge', models.BooleanField(default=False)),
                ('has_sleeping_pods', models.BooleanField(default=False)),
                ('city_access_time', models.IntegerField(default=0, help_text='Minutes to city center')),
                ('layover_quality_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('airline', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('available_seats', models.IntegerField(default=0)),
                ('historical_delay_probability', models.DecimalField(decimal_places=2, default=0.0, help_text='Probability of delay (0-100)', max_digits=5)),
                ('avg_delay_minutes', models.IntegerField(default=0)),
                ('is_mistake_fare', models.BooleanField(default=False)),
                ('normal_price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_flights', to='core.airport')),
                ('origin_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_flights', to='core.airport')),
            ],
            options={
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='FlightConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layover_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost_eur', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('connection_quality_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('is_self_transfer', models.BooleanField(default=False)),
                ('self_transfer_risk', models.DecimalField(decimal_places=2, default=0.0, help_text='Risk percentage for self-transfer (0-100)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_connections', to='core.flight')),
            ],
            options={
                'ordering': ['total_cost_eur', 'total_duration_minutes'],
            },
        ),
        migrations.CreateModel(
            name='GroundTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transport_type', models.CharField(choices=[('train', 'Train'), ('bus', 'Bus'), ('uber', 'Uber/Taxi'), ('car_rental', 'Car Rental'), ('shuttle', 'Airport Shuttle')], max_length=20)),
                ('to_address', models.CharField(blank=True, help_text='Street address if not to airport', max_length=500)),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_eur', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_transports', to='core.airport')),
                ('to_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_transports', to='core.airport')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_sync_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('budget_preference_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_airlines', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(blank=True, help_text='Linked partner for collaborative mode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text='Natural language search query')),
                ('origin_city', models.CharField(blank=True, max_length=100)),
                ('destination_type', models.CharField(blank=True, help_text="e.g., 'warm beach', 'mountain', 'city'", max_length=100)),
                ('max_duration_hours', models.IntegerField(blank=True, null=True)),
                ('max_price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('weather_preference', models.CharField(blank=True, max_length=50)),
                ('ai_confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('ai_parsed_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_destination_address', models.CharField(blank=True, max_length=500)),
                ('total_trip_cost_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_trip_time_minutes', models.IntegerField()),
                ('match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.flight')),
                ('flight_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.flightconnection')),
                ('ground_transport_to_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.groundtransport')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.tripsearch')),
            ],
            options={
                'ordering': ['rank', 'total_trip_cost_eur'],
            },
        ),
        migrations.CreateModel(
            name='PerfectMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfect_matches', to='core.tripoption')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='flightconnection',
            name='ground_transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.groundtransport'),
        ),
        migrations.AddField(
            model_name='flightconnection',
            name='second_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_connections', to='core.flight'),
        ),
        migrations.CreateModel(
            name='DelayPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(help_text="e.g., 'LHR-JFK'", max_length=50)),
                ('airline', models.CharField(max_length=100)),
                ('day_of_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('time_of_day', models.TimeField()),
                ('delay_probability', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('avg_delay_minutes', models.IntegerField(default=0)),
                ('sample_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['route', 'airline'], name='core_delayp_route_956282_idx')],
                'unique_together': {('route', 'airline', 'day_of_week', 'time_of_day')},
            },
        ),
        migrations.CreateModel(
            name='CollaborativeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('super_like', 'Super Like')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.tripoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['latitude', 'longitude'], name='core_airpor_latitud_0e1719_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['city', 'country'], name='core_airpor_city_873b58_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['origin_airport', 'destination_airport', 'departure_time'], name='core_flight_origin__8ad2b2_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['price_eur'], name='core_flight_price_e_08ca34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collaborativevote',
            unique_together={('user', 'trip_option')},
        ),
    ]
