# Generated by Django 6.0.1 on 2026-01-16 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_userprofile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tripoption',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripoption',
            name='saved_by',
            field=models.ManyToManyField(blank=True, help_text='Users who saved this trip', related_name='saved_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tripoption',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.tripsearch'),
        ),
    ]
