# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripoption',
            name='display_data',
            field=models.JSONField(
                blank=True,
                help_text='Flight/offer details when saved from API (no DB flight)',
                null=True
            ),
        ),
    ]
