# Generated by Django 6.0.1 on 2026-02-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('CHF', 'Swiss Franc (CHF)'), ('CNY', 'Chinese Yuan (¥)'), ('INR', 'Indian Rupee (₹)'), ('AED', 'UAE Dirham (AED)'), ('BRL', 'Brazilian Real (R$)'), ('MXN', 'Mexican Peso (MX$)'), ('SGD', 'Singapore Dollar (S$)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('SEK', 'Swedish Krona (SEK)'), ('NOK', 'Norwegian Krone (NOK)'), ('DKK', 'Danish Krone (DKK)'), ('NZD', 'New Zealand Dollar (NZ$)')], default='EUR', help_text='Preferred currency for price display', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('lb', 'Luxembourgish'), ('fa', 'Farsi'), ('es', 'Spanish'), ('it', 'Italian'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('ar', 'Arabic'), ('zh-hans', 'Chinese (Simplified)'), ('ja', 'Japanese'), ('ko', 'Korean'), ('hi', 'Hindi')], default='en', help_text='Preferred UI language code', max_length=10),
        ),
    ]
